"""Add YouTube support

Revision ID: 221647c15953
Revises: 
Create Date: 2025-11-24 18:15:29.037403

"""
from alembic import op
import sqlalchemy as sa

from pgvector.sqlalchemy import Vector
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = '221647c15953'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_url', sa.String(length=500), nullable=False),
    sa.Column('channel_id', sa.String(length=100), nullable=False),
    sa.Column('channel_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('course', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_url')
    )
    op.create_table('video_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=100), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(length=20), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.Column('topic_reference', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube_channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('youtube_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('transcript_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube_channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_embeddings_book_id'))
        batch_op.drop_index(batch_op.f('idx_embeddings_book_page'))
        batch_op.drop_index(batch_op.f('idx_embeddings_hnsw'), postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_exercises_topic'))

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_submissions_exercise'))
        batch_op.drop_index(batch_op.f('idx_submissions_student'))
        batch_op.drop_index(batch_op.f('idx_submissions_student_exercise'))

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=20), server_default='pdf_book', nullable=False))
        batch_op.add_column(sa.Column('video_id', sa.Integer(), nullable=True))
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_topics_book'))
        batch_op.create_foreign_key(None, 'youtube_videos', ['video_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_topics_book'), ['book_id'], unique=False)
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('video_id')
        batch_op.drop_column('source_type')

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_submissions_student_exercise'), ['student_id', 'exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_submissions_student'), ['student_id', sa.literal_column('submitted_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_submissions_exercise'), ['exercise_id', sa.literal_column('submitted_at DESC')], unique=False)

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_exercises_topic'), ['topic_id', sa.literal_column('generated_at DESC')], unique=False)

    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_embeddings_hnsw'), ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
        batch_op.create_index(batch_op.f('idx_embeddings_book_page'), ['book_id', 'page_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_embeddings_book_id'), ['book_id'], unique=False)

    op.drop_table('youtube_videos')
    op.drop_table('video_embeddings')
    op.drop_table('youtube_channels')
    # ### end Alembic commands ###
