"""Add exercise bank management and teacher role

Revision ID: 915aeae985c6
Revises: 221647c15953
Create Date: 2025-11-25 16:58:53.532106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915aeae985c6'
down_revision = '221647c15953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('validated_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('validated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modification_notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['validated_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('modification_notes')
        batch_op.drop_column('validated_at')
        batch_op.drop_column('validated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('status')

    op.drop_table('exercise_usage')
    # ### end Alembic commands ###
