version = 5.1.0
archive_dir = /etc/letsencrypt/archive/nomasceros.es
cert = /etc/letsencrypt/live/nomasceros.es/cert.pem
privkey = /etc/letsencrypt/live/nomasceros.es/privkey.pem
chain = /etc/letsencrypt/live/nomasceros.es/chain.pem
fullchain = /etc/letsencrypt/live/nomasceros.es/fullchain.pem
[renewalparams]
account = c7dfd034336d31c69e67ec26cb47867e
rsa_key_size = 4096
pref_challs = http-01,
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
nomasceros.es = /var/www/certbot
www.nomasceros.es = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-07-12T12:56:53
