from datetime import datetime
from app import db


class Summary(db.Model):
    """
    Model representing a topic summary in the bank.

    Summaries can be:
    - Auto-generated by AI
    - Created manually by teachers
    - Validated by teachers for quality assurance

    Only one summary per topic is allowed.
    """
    __tablename__ = 'summaries'

    # Basic fields
    id = db.Column(db.Integer, primary_key=True)
    topic_id = db.Column(db.Integer, db.ForeignKey('topics.id'), nullable=False)
    content = db.Column(db.Text, nullable=False)
    generated_at = db.Column(db.DateTime, default=datetime.utcnow)

    # Bank management (same pattern as Exercise)
    status = db.Column(db.String(30), default='auto_generated')
    # Status values:
    # - 'auto_generated': Generated by AI, not reviewed
    # - 'pending_validation': Generated but pending review
    # - 'validated': Approved by teacher
    # - 'teacher_created': Manually created by teacher (auto-validated)

    created_by_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=True)
    validated_by_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=True)
    validated_at = db.Column(db.DateTime, nullable=True)
    modification_notes = db.Column(db.Text, nullable=True)

    # Relationships with cascade delete
    topic = db.relationship('Topic', backref='summaries')
    usage_records = db.relationship('SummaryUsage', backref='summary', lazy='dynamic',
                                   cascade='all, delete-orphan')
    created_by = db.relationship('User', foreign_keys=[created_by_id],
                                backref='created_summaries')
    validated_by = db.relationship('User', foreign_keys=[validated_by_id],
                                  backref='validated_summaries')

    def __repr__(self):
        return f'<Summary {self.id} - Topic {self.topic_id} - Status {self.status}>'

    def get_preview(self, length=100):
        """Get a preview of the summary content"""
        if len(self.content) <= length:
            return self.content
        return self.content[:length] + '...'

    def get_usage_count(self):
        """Get number of students who have accessed this summary"""
        from app.models.summary_usage import SummaryUsage
        return SummaryUsage.query.filter_by(summary_id=self.id).count()

    def get_total_accesses(self):
        """Get total number of accesses across all students"""
        from app.models.summary_usage import SummaryUsage
        total = db.session.query(db.func.sum(SummaryUsage.access_count))\
                          .filter_by(summary_id=self.id).scalar()
        return total or 0
